// packages/ui/src/scripts/svelte/Link.svelte
<!-- Hyperlink. -->
<script lang="ts">
/**
 * Copyright (c) Openizr. All Rights Reserved.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */

import { markdown, buildClass } from 'scripts/core/index';

export let href: string;
export let label: string;
export let modifiers = '';
export let id: string | undefined = undefined;
export let rel: string | undefined = undefined;
export let disabled: boolean | undefined = false;
export let target: string | undefined = undefined;
export let onClick: ((event: MouseEvent) => void) | undefined = undefined;

// Enforces props default values.
$: modifiers = (modifiers as string | undefined) ?? '';

$: className = buildClass('ui-link', `${modifiers}${disabled ? ' disabled' : ''}`);

// -----------------------------------------------------------------------------------------------
// CALLBACKS DECLARATION.
// -----------------------------------------------------------------------------------------------

const handleClick = (event: MouseEvent): void => {
  if (onClick !== undefined && !disabled) {
    onClick(event);
  }
};
</script>

<a {id} {rel} {href} class={className} {target} on:click={handleClick} tabIndex={disabled ? -1 : 0}>
  {@html markdown(label)}
</a>

// packages/ui/src/scripts/react/Link.tsx
/**
 * Copyright (c) Openizr. All Rights Reserved.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */

import * as React from 'react';
import { buildClass } from 'scripts/core/index';

/**
 * Hyperlink.
 */
function UILink(props: UILinkProps): JSX.Element {
  const { rel, id, itemProp } = props;
  const { href, label, disabled = false } = props;
  const { onClick, modifiers = '', target } = props;

  // -----------------------------------------------------------------------------------------------
  // CALLBACKS DECLARATION.
  // -----------------------------------------------------------------------------------------------

  const handleClick = (event: React.MouseEvent<HTMLAnchorElement>): void => {
    if (onClick !== undefined && !disabled) {
      onClick(event as unknown as MouseEvent);
    }
  };

  // -----------------------------------------------------------------------------------------------
  // COMPONENT RENDERING.
  // -----------------------------------------------------------------------------------------------

  return (
    <a
      id={id}
      rel={rel}
      href={href}
      target={target}
      itemProp={itemProp}
      onClick={handleClick}
      tabIndex={disabled ? -1 : 0}
      className={buildClass('ui-link', `${modifiers}${disabled ? ' disabled' : ''}`)}
    >
      {label}
    </a>
  );
}

export default React.memo(UILink);
