// packages/ui/src/__playground__/pages/Home.tsx
/* c8 ignore start */

import * as React from 'react';

export default function Home(): JSX.Element {
  return (
    <div className="vgap-5">
      <main className="ui-page ui-block cols-3 hgap-3 vgap-5">
        <a href="/react/typography" className="cols-3">TYPOGRAPHY</a>
        <br />
        <a href="/react/images" className="cols-3">IMAGES</a>
        <br />
        <a href="/react/buttons" className="cols-3">BUTTONS</a>
        <br />
        <a href="/react/options" className="cols-3">OPTIONS</a>
        <br />
        <a href="/react/textfields" className="cols-3">TEXTFIELDS</a>
        <br />
        <a href="/react/textareas" className="cols-3">TEXTAREAS</a>
        <br />
        <a href="/react/file-pickers" className="cols-3">FILE PICKERS</a>
        <br />
        <a href="/react/tooltips" className="cols-3">TOOLTIPS</a>
      </main>
    </div>
  );
}

// packages/ui/src/__playground__/pages/Home.svelte
/* c8 ignore start */

<script lang="ts"></script>

<div class="vgap-5">
  <main class="ui-page ui-block cols-3 hgap-3 vgap-5">
    <a href="/svelte/typography" class="cols-3">TYPOGRAPHY</a>
    <br />
    <a href="/svelte/images" class="cols-3">IMAGES</a>
    <br />
    <a href="/svelte/buttons" class="cols-3">BUTTONS</a>
    <br />
    <a href="/svelte/options" class="cols-3">OPTIONS</a>
    <br />
    <a href="/svelte/textfields" class="cols-3">TEXTFIELDS</a>
    <br />
    <a href="/svelte/textareas" class="cols-3">TEXTAREAS</a>
    <br />
    <a href="/svelte/file-pickers" class="cols-3">FILE PICKERS</a>
    <br />
    <a href="/svelte/tooltips" class="cols-3">TOOLTIPS</a>
  </main>
</div>
