// packages/ui/src/__playground__/pages/Images.svelte
/* c8 ignore start */

<script lang="ts">
  import { UIImage } from 'scripts/svelte/index';
</script>

<div class="vgap-5">
  <main class="grid cols-3 hgap-3 vgap-5 items-center">
    <a href="/svelte" class="cols-3">GO BACK</a>
    <UIImage ratio="square" src="https://picsum.photos/200/600" alt="img" />
    <UIImage ratio="square" src="https://picsum.photos/300/300" alt="img" />
    <UIImage ratio="square" src="https://picsum.photos/600/200" alt="img" />
    <UIImage ratio="square" src="https://picsum.photos/200/600" alt="img" />
    <UIImage ratio="150x250" src="https://picsum.photos/300/300" alt="img" />
    <UIImage ratio="panoramic" src="https://picsum.photos/600/200" alt="img" />
    <UIImage ratio="landscape" src="https://picsum.photos/200/600" alt="img" />
    <UIImage ratio="portrait" src="https://picsum.photos/300/300" alt="img" />
    <UIImage ratio="portrait" src="https://picsum.photos/600/200" alt="img" />
  </main>
</div>

// packages/ui/src/__playground__/pages/Images.tsx
/* c8 ignore start */

import { UIImage } from 'scripts/react/index';

export default function Images(): JSX.Element {
  return (
    <div>
      <main className="grid cols-3 hgap-3 vgap-5 items-center">
        <a href="/react" className="cols-3">GO BACK</a>
        <UIImage ratio="square" src="https://picsum.photos/200/600" alt="img" />
        <UIImage ratio="square" src="https://picsum.photos/300/300" alt="img" />
        <UIImage ratio="square" src="https://picsum.photos/600/200" alt="img" />
        <UIImage ratio="square" src="https://picsum.photos/200/600" alt="img" />
        <UIImage ratio="150x250" src="https://picsum.photos/300/300" alt="img" />
        <UIImage ratio="panoramic" src="https://picsum.photos/600/200" alt="img" />
        <UIImage ratio="landscape" src="https://picsum.photos/200/600" alt="img" />
        <UIImage ratio="portrait" src="https://picsum.photos/300/300" alt="img" />
        <UIImage ratio="portrait" src="https://picsum.photos/600/200" alt="img" />
      </main>
    </div>
  );
}
