// packages/client/src/scripts/react/components/Loader.tsx
/**
 * Copyright (c) Openizr. All Rights Reserved.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */

import * as React from 'react';
import { type DefaultDataModel } from '@perseid/core';

/**
 * App loader.
 *
 * @linkcode https://github.com/openizr/perseid/blob/main/client/src/scripts/react/components/Loader.tsx
 */
function Loader<DataModel extends DefaultDataModel = DefaultDataModel>({
  services,
}: ReactCommonProps<DataModel>): JSX.Element {
  return (
    <div className="loader">
      {services.i18n.t('LOADER.LABEL')}
    </div>
  );
}

export default React.memo(Loader) as ReactLoaderComponent;

// packages/client/src/scripts/vue/components/Loader.vue
<!--
  App loader.

  @linkcode https://github.com/openizr/perseid/blob/main/packages/client/src/scripts/vue/components/Loader.vue
-->
<script lang="ts" setup>
/**
 * Copyright (c) Openizr. All Rights Reserved.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */

import type BaseModel from 'scripts/core/services/Model';
import type BaseStore from 'scripts/core/services/Store';
import type BaseApiClient from 'scripts/core/services/ApiClient';
import type { UseSubscription } from '@perseid/store/connectors/vue';
import { I18n as BaseI18n, type DefaultDataModel } from '@perseid/core';

/**
 * Loader props.
 */
export interface LoaderProps<
  DataModel extends DefaultDataModel = DefaultDataModel,
  I18n extends BaseI18n = BaseI18n,
  Store extends BaseStore<DataModel> = BaseStore<DataModel>,
  Model extends BaseModel<DataModel> = BaseModel<DataModel>,
  ApiClient extends BaseApiClient<DataModel> = BaseApiClient<DataModel>,
> {
  /** Perseid client services instances. */
  services: {
    /** I18n instance. */
    i18n: I18n;

    /** Perseid store instance. */
    store: Store & { useSubscription: UseSubscription; };

    /** Perseid model instance. */
    model: Model;

    /** API client instance. */
    apiClient: ApiClient;
  };
}

defineProps<LoaderProps>();
</script>

<template>
  <div class="loader">
    {{ services.i18n.t('LOADER.LABEL') }}
  </div>
</template>
