// packages/client/src/scripts/react/components/NestedFields.tsx
/**
 * Copyright (c) Openizr. All Rights Reserved.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */

import * as React from 'react';
import { type Fields } from '@perseid/form';
import { type FormFieldProps } from '@perseid/form/react';
import { buildClass, UIButton, type UIButtonProps } from '@perseid/ui/react';

/**
 * Nested fields props.
 */
export interface NestedFieldsProps extends FormFieldProps {
  _canonicalPath?: string;

  /** `id` HTML attribute to set to the element. */
  id?: string;

  /** Initial field value. */
  value: unknown[];

  /** Element's label. Supports light markdown. */
  label?: string;

  /** Element's helper. Supports light markdown. */
  helper?: string;

  /** List of modifiers to apply to the element. Defaults to `""`. */
  modifiers?: string;

  /** Minimum items allowed for this field. Defaults to `0`. */
  minItems?: number;

  /** Maximum items allowed for this field. Defaults to `Infinity`. */
  maxItems?: number;

  /** Add item button props. */
  addButtonProps?: UIButtonProps;

  /** Remove item button props. */
  removeButtonProps?: UIButtonProps;

  /** Field sub-fields list. */
  fields: Fields;

  /** Field component to use for rendering. */
  Field: (props: FormFieldProps & { _canonicalPath?: string; }) => JSX.Element;
}

/**
 * Nested fields (array / object) form component.
 *
 * @linkcode https://github.com/openizr/perseid/blob/main/packages/client/src/scripts/react/components/NestedFields.tsx
 */
function NestedFields({
  id,
  type,
  path,
  Field,
  label,
  value,
  helper,
  engine,
  fields,
  isActive,
  modifiers,
  activeStep,
  minItems = 0,
  setActiveStep,
  _canonicalPath,
  addButtonProps,
  useSubscription,
  removeButtonProps,
  maxItems = Infinity,
}: NestedFieldsProps): JSX.Element {
  const [currentFields, setCurrentFields] = React.useState<Fields>(fields);
  const className = buildClass('ui-nested-fields', [modifiers, type].join(' '));

  const addItem = React.useCallback(() => {
    const newValue = (value as unknown[] | null ?? []).concat([null]);
    engine.userAction({ path, type: 'input', data: newValue });
  }, [engine, path, value]);

  const removeItem = React.useCallback((index: number) => (): void => {
    setCurrentFields((previousState) => (
      previousState.slice(0, index).concat(previousState.slice(index + 1))
    ));
    const newValue = value.slice(0, index).concat(value.slice(index + 1));
    engine.userAction({ path, type: 'input', data: newValue });
  }, [engine, path, value]);

  // Updates current fields whenever `fields` prop changes.
  React.useEffect(() => {
    setCurrentFields(fields);
  }, [fields]);

  // Adds new fields if length does not fit minimum length.
  React.useEffect(() => {
    if (type === 'array' && value as unknown !== null && value.length < minItems) {
      const newValue = value.concat(new Array(minItems - value.length).fill(null));
      engine.userAction({ path, type: 'input', data: newValue });
    }
  }, [minItems, engine, value, path, type]);

  // Removes extra fields if length does not fit maximum length.
  React.useEffect(() => {
    if (type === 'array' && value as unknown !== null && value.length > maxItems) {
      setCurrentFields((previousState) => previousState.slice(0, maxItems));
      const newValue = value.slice(0, maxItems);
      engine.userAction({ path, type: 'input', data: newValue });
    }
  }, [engine, value, maxItems, path, type]);

  return (
    <div id={id} className={className}>
      {(label !== undefined) && <span className="ui-nested-fields__label">{label}</span>}

      {currentFields.map((field, index) => ((field === null) ? null : (
        <div className="ui-nested-fields__field" key={field.path}>
          {(type !== 'object' && currentFields.length > minItems) && (
            <UIButton
              type="button"
              icon="delete"
              onClick={removeItem(index)}
              {...removeButtonProps}
            />
          )}
          <Field
            {...field}
            Field={Field}
            engine={engine}
            isActive={isActive}
            activeStep={activeStep}
            isRequired={field.required}
            setActiveStep={setActiveStep}
            useSubscription={useSubscription}
            _canonicalPath={`${String(_canonicalPath)}.${String(type === 'array' ? '$n' : field.path.split('.').at(-1))}`}
          />
        </div>
      )))}

      {(type === 'array') && (
        <UIButton
          icon="plus"
          onClick={addItem}
          disabled={currentFields.length >= maxItems}
          {...addButtonProps}
        />
      )}
      {(helper !== undefined) && <span className="ui-nested-fields__helper">{helper}</span>}
    </div>
  );
}

export default React.memo(NestedFields);

// packages/client/src/scripts/vue/components/NestedFields.vue
<!--
  Nested fields (array / object) form component.

  @linkcode https://github.com/openizr/perseid/blob/main/packages/client/src/scripts/vue/components/NestedFields.vue
-->
<script lang="ts" setup>
/**
 * Copyright (c) Openizr. All Rights Reserved.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */

import { ref, watch, type DefineComponent } from 'vue';
import { buildClass, UIButton } from '@perseid/ui/vue';

const props = withDefaults(defineProps<{
  id?: string;
  path: string;
  type: string;
  label?: string;
  status: string;
  value: unknown;
  helper?: string;
  minItems: number;
  maxItems?: number;
  isActive: boolean;
  modifiers: string;
  activeStep?: string;
  error: string | null;
  _canonicalPath?: string;
  Field: DefineComponent<unknown>;
  setActiveStep:(path: string) => void;
  useSubscription:(id: string) => unknown;
  additionalProps: Record<string, unknown>;
  addButtonProps?: Record<string, unknown>;
  removeButtonProps?: Record<string, unknown>;
  fields: {
    path: string;
    required: boolean;
    type: string;
    value: unknown;
    status: string;
    fields?: unknown[];
    error: string | null;
  }[];
  engine: { userAction:(params: { path: string; type: string; data: unknown; }) => void; };
}>(), {
  minItems: 0,
  modifiers: '',
  id: undefined,
  label: undefined,
  helper: undefined,
  maxItems: Infinity,
  activeStep: undefined,
  _canonicalPath: undefined,
  addButtonProps: undefined,
  removeButtonProps: undefined,

});

const currentFields = ref(props.fields);
const className = buildClass('ui-nested-fields', [props.modifiers, props.type].join(' '));

const addItem = () => {
  const newValue = ((props.value as null | unknown[]) ?? []).concat([null]);
  props.engine.userAction({ path: props.path, type: 'input', data: newValue });
};

const removeItem = (index: number) => (): void => {
  currentFields.value = currentFields.value.slice(0, index)
    .concat(currentFields.value.slice(index + 1));
  const value = props.value as unknown[];
  const newValue = value.slice(0, index).concat(value.slice(index + 1));
  props.engine.userAction({ path: props.path, type: 'input', data: newValue });
};

// Updates current fields whenever `fields` prop changes.
watch(() => props.fields, () => {
  currentFields.value = props.fields;
});

// Adds new fields if length does not fit minimum length.
watch(() => props.minItems, () => {
  const value = props.value as unknown[] | null;
  if (props.type === 'array' && value !== null && value.length < props.minItems) {
    const newValue = value.concat(new Array(props.minItems - value.length).fill(null));
    props.engine.userAction({ path: props.path, type: 'input', data: newValue });
  }
});

// Removes extra fields if length does not fit maximum length.
watch(() => props.maxItems, () => {
  const value = props.value as unknown[] | null;
  if (props.type === 'array' && value !== null && value.length > props.maxItems) {
    currentFields.value = currentFields.value.slice(0, props.maxItems);
    const newValue = value.slice(0, props.maxItems);
    props.engine.userAction({ path: props.path, type: 'input', data: newValue });
  }
});
</script>

<template>
  <div :id="id" :class="className">
    <span v-if="label !== undefined" class="ui-nested-fields__label">{{ label }}</span>
    <div
      v-for="(field, index) in currentFields.filter((field) => field !== null)"
      :key="field.path"
      class="ui-nested-fields__field"
    >
      <UIButton
        v-if="type !== 'object' && currentFields.length > minItems"
        type="button"
        icon="delete"
        :onClick="removeItem(index)"
        v-bind="removeButtonProps"
      />
      <component
        :is="Field"
        :Field="Field"
        :engine="engine"
        :type="field.type"
        :path="field.path"
        :value="field.value"
        :error="field.error"
        :isActive="isActive"
        :status="field.status"
        :fields="field.fields"
        :activeStep="activeStep"
        :isRequired="field.required"
        :setActiveStep="setActiveStep"
        :additionalProps="{
          ...additionalProps,
          _canonicalPath: `${String(_canonicalPath)}.${String(type === 'array'
            ? '$n' : field.path.split('.').at(-1))}`
        }"
        :useSubscription="useSubscription"
      />
    </div>
    <UIButton
      v-if="type === 'array'"
      icon="plus"
      :onClick="addItem"
      :disabled="currentFields.length >= maxItems"
      v-bind="addButtonProps"
    />
    <span v-if="helper !== undefined" class="ui-nested-fields__helper">{{ helper }}</span>
  </div>
</template>
