// packages/client/src/scripts/vue/components/FormField.vue
<!--
  Generic form field.

  @linkcode https://github.com/openizr/perseid/blob/main/packages/client/src/scripts/vue/components/FormField.vue
-->
<script lang="ts" setup>
/**
 * Copyright (c) Openizr. All Rights Reserved.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */

import {
  Id,
  toSnakeCase,
  I18n as BaseI18n,
  type DefaultDataModel,
} from '@perseid/core';
import {
  markdown,
  UIButton,
  UIOptions,
  buildClass,
  UITextarea,
  UITextfield,
  UIFilePicker,
  type UIOptionsOption,
} from '@perseid/ui/vue';
import type Engine from '@perseid/form';
import { type Field as FormField } from '@perseid/form';
import type BaseModel from 'scripts/core/services/Model';
import type BaseStore from 'scripts/core/services/Store';
import { computed, onMounted, type DefineComponent } from 'vue';
import type BaseApiClient from 'scripts/core/services/ApiClient';
import NestedFields from 'scripts/vue/components/NestedFields.vue';
import { type UseSubscription } from '@perseid/store/connectors/vue';
import OptionalField from 'scripts/vue/components/OptionalField.vue';
import LazyOptions, { type LazyOptionsProps } from 'scripts/vue/components/LazyOptions.vue';

/**
 * Generic form field props.
 */
export interface FormFieldProps<T extends Engine = Engine> {
  /** Instance of the form engine. */
  engine: T;

  /** Whether field belongs to current active step. */
  isActive: boolean;

  /** Path of the currently active step. */
  activeStep?: string;

  /** Field type. */
  type: FormField['type'];

  /** Field full path in the form. */
  path: FormField['path'];

  /** Field value. */
  value: FormField['value'];

  /** Field error, if any. */
  error: FormField['error'];

  /** Field status. */
  status: FormField['status'];

  /** Field sub-fields (for objects and arrays only). */
  fields?: FormField['fields'];

  /** Whether field is required. */
  isRequired: boolean;

  /** Field component to use for rendering. */
  Field: DefineComponent<unknown>;

  /** Changes current active step. */
  setActiveStep: (stepPath: string) => void;

  /** Store `useSubscription` function, you can use it to directly subscribe to form state. */
  useSubscription: UseSubscription;

  additionalProps?: Record<string, unknown>;
}

const dateRegExp = /^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}\.[0-9]{3}Z$/;

const props = defineProps<FormFieldProps>();

const additionalProps = computed(() => (props.additionalProps ?? {}) as {
    _canonicalPath?: string;

    fieldProps: Partial<Record<string, {
      /** Name of the component to use for that field. */
      component: string;

      /** Component props for that field. */
      componentProps?: Record<string, unknown>;
    }>>;
    context: {
      prefix: string;
      services: {
        /** I18n instance. */
        i18n: BaseI18n;

        /** Perseid store instance. */
        store: BaseStore & { useSubscription: UseSubscription; };

        /** Perseid model instance. */
        model: BaseModel;

        /** API client instance. */
        apiClient: BaseApiClient;
      };
    };
});
const shortPath = additionalProps.value._canonicalPath ?? props.path.split('.').slice(2).join('.');
const context = computed(() => additionalProps.value.context);
const fieldConfiguration = computed<Record<string, unknown> | undefined>(() => (
  additionalProps.value.fieldProps[props.path] ?? additionalProps.value.fieldProps[shortPath]
));
const componentProps = computed<Record<string, unknown>>(() => {
  const finalProps = (fieldConfiguration.value?.componentProps ?? {}) as Record<string, unknown>;
  const { options, placeholder, ...rest } = finalProps;
  if (options || placeholder) {
    // No-op.
  }
  return rest;
});
const allComponentProps = computed<Record<string, unknown>>(() => (
  (fieldConfiguration.value?.componentProps ?? {}) as Record<string, unknown>
));
const modifiers = computed(() => {
  const baseModifiers = ((fieldConfiguration.value?.componentProps as Record<
    string, Record<string, string>
  > | null)?.componentProps?.modifiers) ?? '';
  return `${props.status} ${props.isRequired ? 'required' : ''} ${baseModifiers}`;
});

const fieldPath = computed(() => toSnakeCase(shortPath.replace(/\./g, '.fields.').replace(/\.\$n/g, '')));
const labels = computed(() => ({
  label: context.value.services.i18n.t(`${context.value.prefix}.FIELDS.${fieldPath.value}.LABEL`),
  helper: !props.error ? undefined : context.value.services.i18n.t(`${context.value.prefix}.FIELDS.${fieldPath.value}.ERRORS.${props.error}`),
  placeholder: !allComponentProps.value.placeholder ? undefined : context.value.services.i18n.t(`${context.value.prefix}.FIELDS.${fieldPath.value}.${String(allComponentProps.value.placeholder)}`),
  options: (allComponentProps.value.options as UIOptionsOption[] | undefined)?.map((option) => ({
    ...option,
    label: context.value.services.i18n.t(`${context.value.prefix}.FIELDS.${fieldPath.value}.OPTIONS.${option.label}`),
  })),
}));

// Sets default value to `false` for boolean fields.
onMounted(() => {
  if (fieldConfiguration.value?.component === 'Options' && props.type === 'boolean' && props.value === null) {
    props.engine.userAction({ type: 'input', path: props.path, data: false });
  }
});
</script>

<template>
  <UIButton
    v-if="fieldConfiguration?.component === 'Button'"
    :label="labels.label"
    :modifiers="modifiers"
    :on-click="() => (engine as Engine).userAction({ type: 'input', path, data: true })"
    v-bind="componentProps"
  />
  <UITextfield
    v-else-if="fieldConfiguration?.component === 'Textfield'"
    :name="path"
    :label="labels.label"
    :modifiers="modifiers"
    :debounce-timeout="100"
    :helper="labels.helper"
    :placeholder="labels.placeholder"
    :value="(value as string | undefined) ?? undefined"
    :readonly="!isActive || componentProps.readOnly as boolean"
    v-bind="componentProps"
    :on-change="(newValue): void => {
      if (newValue !== value) {
        (engine as Engine).userAction({ type: 'input', path, data: newValue });
      }
    }"
  />
  <UITextarea
    v-else-if="fieldConfiguration?.component === 'Textarea'"
    :name="path"
    :label="labels.label"
    :modifiers="modifiers"
    :debounce-timeout="100"
    :helper="labels.helper"
    :placeholder="labels.placeholder"
    :value="(value as string | undefined) ?? undefined"
    :readonly="!isActive || componentProps.readOnly as boolean"
    :on-change="(newValue): void => {
      (engine as Engine).userAction({ type: 'input', path, data: newValue });
    }"
    v-bind="componentProps"
  />
  <UITextfield
    v-else-if="fieldConfiguration?.component === 'DatePicker'"
    :name="path"
    :modifiers="modifiers"
    :debounce-timeout="100"
    :label="labels.label"
    :helper="labels.helper"
    :placeholder="labels.placeholder"
    :readonly="!isActive || componentProps.readOnly as boolean"
    :value="value instanceof Date ? (value).toISOString() : undefined"
    :on-change="(newValue): void => {
      (engine as Engine).userAction({
        path,
        type: 'input',
        data: dateRegExp.test(newValue) ? new Date(newValue) : null,
      });
    }"
    v-bind="componentProps"
  />
  <UIFilePicker
    v-else-if="fieldConfiguration?.component === 'FilePicker'"
    :name="path"
    :modifiers="modifiers"
    :label="labels.label"
    :helper="labels.helper"
    :placeholder="labels.placeholder"
    :value="(value as File | undefined) ?? undefined"
    :on-change="(newValue): void => {
      (engine as Engine).userAction({ type: 'input', path, data: newValue });
    }"
    v-bind="componentProps"
  />
  <UIOptions
    v-else-if="fieldConfiguration?.component === 'Options'"
    :name="path"
    :label="labels.label"
    :modifiers="modifiers"
    :helper="labels.helper"
    :placeholder="labels.placeholder"
    :options="labels.options as UIOptionsOption[]"
    :value="(type === 'boolean') ? String(value) : (value as string | undefined) ?? undefined"
    :on-change="(newValue: string[]): void => {
      const data = (type === 'boolean' && componentProps.multiple)
        ? newValue[1] === 'true'
        : newValue;
      (engine as Engine).userAction({ type: 'input', path, data });
    }"
    v-bind="componentProps"
  />
  <section
    v-if="fieldConfiguration?.component === 'Message'"
    :class="buildClass('ui-message', modifiers)"
    v-html="markdown(labels.label, false)"
  />
  <OptionalField
    v-else-if="(
      fieldConfiguration?.component === 'Array' || fieldConfiguration?.component === 'Object'
    ) && !isRequired"
    :type="type"
    :path="path"
    :Field="Field"
    :error="error"
    :value="value"
    :fields="fields"
    :engine="engine"
    :status="status"
    :isActive="isActive"
    :isRequired="isRequired"
    :activeStep="activeStep"
    :_canonicalPath="shortPath"
    :setActiveStep="setActiveStep"
    :useSubscription="useSubscription"
    :additionalProps="additionalProps"
    :modifiers="fieldConfiguration.component.toLowerCase()"
    :showLabel="additionalProps.context.services.i18n.t(
      `${additionalProps.context.prefix}.FIELDS.${fieldPath}.SHOW.LABEL`
    )"
    :hideLabel="additionalProps.context.services.i18n.t(
      `${additionalProps.context.prefix}.FIELDS.${fieldPath}.HIDE.LABEL`
    )"
    v-bind="componentProps"
  />
  <NestedFields
    v-else-if="(
      fieldConfiguration?.component === 'Array' || fieldConfiguration?.component === 'Object'
    ) && isRequired"
    :type="type"
    :path="path"
    :Field="Field"
    :error="error"
    :engine="engine"
    :status="status"
    :isActive="isActive"
    :isRequired="isRequired"
    :activeStep="activeStep"
    :value="value as unknown[]"
    :_canonicalPath="shortPath"
    :fields="fields as FormField[]"
    :setActiveStep="setActiveStep"
    :useSubscription="useSubscription"
    :additionalProps="additionalProps"
    :minItems="componentProps.minItems as number"
    :maxItems="componentProps.maxItems as number"
    :modifiers="fieldConfiguration.component.toLowerCase()"
    v-bind="componentProps"
  />
  <LazyOptions
    v-else-if="fieldConfiguration?.component === 'LazyOptions'"
    :label="labels.label"
    :modifiers="modifiers"
    :store="context.services.store"
    :helper="labels.helper"
    loadingLabel="loading..."
    noResultLabel="no result..."
    :placeholder="labels.placeholder"
    :value="(value !== null && value !== undefined) ? String(value) : undefined"
    :resource="componentProps.resource as LazyOptionsProps<DefaultDataModel>['resource']"
    :labelFn="componentProps.labelFn as LazyOptionsProps<DefaultDataModel>['labelFn']"
    :loadResults="componentProps.loadResults as LazyOptionsProps<DefaultDataModel>['loadResults']"
    v-bind="componentProps"
    :onChange="(option): void => {
      (engine as Engine).userAction({
        type: 'input', path, data: option?.value ? new Id(option.value) : null
      });
    }"
  />
</template>

// packages/client/src/scripts/react/components/FormField.tsx
/**
 * Copyright (c) Openizr. All Rights Reserved.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */

import {
  markdown,
  UIButton,
  UIOptions,
  buildClass,
  UITextarea,
  UITextfield,
  UIFilePicker,
  type UIOptionsOption,
} from '@perseid/ui/react';
import * as React from 'react';
import { type Fields } from '@perseid/form';
import { type FormFieldProps } from '@perseid/form/react';
import NestedFields from 'scripts/react/components/NestedFields';
import OptionalField from 'scripts/react/components/OptionalField';
import { toSnakeCase, type DefaultDataModel, Id } from '@perseid/core';
import LazyOptions, { type LazyOptionsProps } from 'scripts/react/components/LazyOptions';

const dateRegExp = /^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}\.[0-9]{3}Z$/;

/**
 * Generic form field.
 *
 * @linkcode https://github.com/openizr/perseid/blob/main/packages/client/src/scripts/react/components/FormField.tsx
 */
export default function FormField(
  fieldProps: FormDefinition['fieldProps'],
  context: { prefix: string; services: ReactCommonProps['services']; },
): React.FC<FormFieldProps & { _canonicalPath?: string; }> {
  return React.memo(({
    type,
    path,
    Field,
    error,
    value,
    engine,
    status,
    fields,
    isActive,
    isRequired,
    _canonicalPath,
    useSubscription,
    ...rest
  }: FormFieldProps & { _canonicalPath?: string; }) => {
    const { services, prefix } = context;
    const shortPath = _canonicalPath ?? path.split('.').slice(2).join('.');
    const fieldConfiguration = fieldProps[path] ?? fieldProps[shortPath];
    const { options, placeholder, ...componentProps } = fieldConfiguration?.componentProps ?? {};
    let modifiers = (fieldConfiguration?.componentProps?.modifiers as string | undefined) ?? '';
    modifiers = `${status} ${isRequired ? 'required' : ''} ${modifiers}`;

    const fieldPath = React.useMemo(() => (
      toSnakeCase(shortPath.replace(/\./g, '.fields.').replace(/\.\$n/g, ''))
    ), [shortPath]);

    const labels = React.useMemo(() => ({
      label: services.i18n.t(`${prefix}.FIELDS.${fieldPath}.LABEL`),
      helper: !error ? undefined : services.i18n.t(`${prefix}.FIELDS.${fieldPath}.ERRORS.${error}`),
      placeholder: !placeholder ? undefined : services.i18n.t(`${prefix}.FIELDS.${fieldPath}.${String(placeholder)}`),
      options: (options as UIOptionsOption[] | undefined)?.map((option) => ({
        ...option,
        label: services.i18n.t(`${prefix}.FIELDS.${fieldPath}.OPTIONS.${option.label}`),
      })),
    }), [services, fieldPath, options, prefix, error, placeholder]);

    // Sets default value to `false` for boolean fields.
    React.useEffect(() => {
      if (fieldConfiguration?.component === 'Options' && type === 'boolean' && value === null) {
        engine.userAction({ type: 'input', path, data: false });
      }
    }, [engine, fieldConfiguration?.component, path, type, value]);

    if (fieldConfiguration?.component === 'Button') {
      return (
        <UIButton
          label={labels.label}
          modifiers={modifiers}
          onClick={(): void => { engine.userAction({ type: 'input', path, data: true }); }}
          {...componentProps}
        />
      );
    }

    if (fieldConfiguration?.component === 'Textfield') {
      return (
        <UITextfield
          name={path}
          label={labels.label}
          modifiers={modifiers}
          debounceTimeout={100}
          helper={labels.helper}
          placeholder={labels.placeholder}
          value={(value as string | undefined) ?? undefined}
          readonly={!isActive || componentProps.readOnly as boolean}
          onChange={(newValue): void => {
            if (newValue !== value) {
              engine.userAction({ type: 'input', path, data: newValue });
            }
          }}
          {...componentProps}
        />
      );
    }

    if (fieldConfiguration?.component === 'Textarea') {
      return (
        <UITextarea
          name={path}
          label={labels.label}
          modifiers={modifiers}
          debounceTimeout={100}
          helper={labels.helper}
          placeholder={labels.placeholder}
          value={(value as string | undefined) ?? undefined}
          readonly={!isActive || componentProps.readOnly as boolean}
          onChange={(newValue): void => {
            engine.userAction({ type: 'input', path, data: newValue });
          }}
          {...componentProps}
        />
      );
    }

    if (fieldConfiguration?.component === 'DatePicker') {
      return (
        <UITextfield
          name={path}
          modifiers={modifiers}
          debounceTimeout={100}
          label={labels.label}
          helper={labels.helper}
          placeholder={labels.placeholder}
          readonly={!isActive || componentProps.readOnly as boolean}
          value={value instanceof Date ? (value).toISOString() : undefined}
          onChange={(newValue): void => {
            engine.userAction({
              path,
              type: 'input',
              data: dateRegExp.test(newValue) ? new Date(newValue) : null,
            });
          }}
          {...componentProps}
        />
      );
    }

    if (fieldConfiguration?.component === 'FilePicker') {
      return (
        <UIFilePicker
          name={path}
          modifiers={modifiers}
          label={labels.label}
          helper={labels.helper}
          placeholder={labels.placeholder}
          value={(value as File | undefined) ?? undefined}
          onChange={(newValue): void => {
            engine.userAction({ type: 'input', path, data: newValue });
          }}
          {...componentProps}
        />
      );
    }

    if (fieldConfiguration?.component === 'Options') {
      return (
        <UIOptions
          name={path}
          label={labels.label}
          modifiers={modifiers}
          helper={labels.helper}
          placeholder={labels.placeholder}
          options={labels.options as UIOptionsOption[]}
          value={(type === 'boolean') ? String(value) : (value as string | undefined) ?? undefined}
          onChange={(newValue): void => {
            const data = (type === 'boolean' && componentProps.multiple) ? newValue[1] === 'true' : newValue;
            engine.userAction({ type: 'input', path, data });
          }}
          {...componentProps}
        />
      );
    }

    if (fieldConfiguration?.component === 'Message') {
      return (
        <section
          className={buildClass('ui-message', modifiers)}
          dangerouslySetInnerHTML={{ __html: markdown(labels.label, false) }}
        />
      );
    }

    if (fieldConfiguration?.component === 'Array' || fieldConfiguration?.component === 'Object') {
      if (!isRequired) {
        return (
          <OptionalField
            type={type}
            path={path}
            error={error}
            value={value}
            fields={fields}
            engine={engine}
            status={status}
            isActive={isActive}
            isRequired={isRequired}
            _canonicalPath={shortPath}
            useSubscription={useSubscription}
            modifiers={fieldConfiguration.component.toLowerCase()}
            Field={Field as unknown as (props: FormFieldProps) => JSX.Element}
            showLabel={services.i18n.t(`${prefix}.FIELDS.${fieldPath}.SHOW.LABEL`)}
            hideLabel={services.i18n.t(`${prefix}.FIELDS.${fieldPath}.HIDE.LABEL`)}
            {...rest}
          />
        );
      }
      return (
        <NestedFields
          type={type}
          path={path}
          error={error}
          engine={engine}
          status={status}
          isActive={isActive}
          label={labels.label}
          modifiers={modifiers}
          helper={labels.helper}
          isRequired={isRequired}
          value={value as unknown[]}
          useSubscription={useSubscription}
          fields={fields as unknown as Fields}
          {...rest}
          Field={Field as unknown as (props: FormFieldProps) => JSX.Element}
          _canonicalPath={shortPath}
          {...fieldConfiguration.componentProps}
        />
      );
    }

    if (fieldConfiguration?.component === 'LazyOptions') {
      return (
        <LazyOptions
          label={labels.label}
          modifiers={modifiers}
          store={services.store}
          helper={labels.helper}
          loadingLabel="loading..."
          noResultLabel="no result..."
          placeholder={labels.placeholder}
          value={(value !== null && value !== undefined) ? String(value) : undefined}
          resource={componentProps.resource as LazyOptionsProps<DefaultDataModel>['resource']}
          labelFn={componentProps.labelFn as LazyOptionsProps<DefaultDataModel>['labelFn']}
          loadResults={componentProps.loadResults as LazyOptionsProps<DefaultDataModel>['loadResults']}
          {...componentProps}
          onChange={(option): void => {
            engine.userAction({ type: 'input', path, data: option?.value ? new Id(option.value) : null });
          }}
        />
      );
    }

    return null;
  });
}
