// packages/dev-kit/src/__playground__/frontend/src/scripts/containers/Router.tsx
import * as React from 'react';
import store from 'scripts/store';
import routes from 'scripts/store/routes';
import useStore from 'diox/connectors/react';
import Loader from 'scripts/components/Loader';
import translate from 'scripts/helpers/translate';

type LazyComponent = () => Promise<{
  default: React.ComponentType<{
    translate: (label: string, values: Record<string, string>) => string
  }>
}>;

const useCombiner = useStore(store); // eslint-disable-line react-hooks/rules-of-hooks

/**
 * App router.
 */
export default function Router(props: { locale: unknown; }): JSX.Element {
  const { log } = console;
  const { locale } = props;
  log(locale);
  const route = useCombiner('router', (newState: { route: string; }) => newState.route);
  const component = routes[route] as LazyComponent | undefined;
  let currentPage = null;
  if (component !== undefined) {
    const Component = React.lazy(component);
    currentPage = <Component translate={translate} />;
  }

  const { Suspense } = React;

  return (
    <Suspense fallback={<Loader />}>
      {currentPage}
    </Suspense>
  );
}

Router.propTypes = {};
Router.displayName = 'Router';

// packages/dev-kit/testing/frontend/src/scripts/containers/Router.svelte
<script lang="ts">
  import { onDestroy } from 'svelte';
  import routes from 'scripts/store/routes';
  import useCombiner from 'scripts/store/useCombiner';
  import Loader from 'scripts/components/Loader.svelte';

  type Any = any; // eslint-disable-line
  export let locale: Record<string, string>;
  let component: { default: Any; } | null = { default: Loader };
  const router = useCombiner<{ route: string; }>('router', (newState: Any) => newState as unknown);
  const unsubscribe = router.subscribe((newState) => {
    const page = routes[newState.route] as (() => Promise<{ default: unknown; }>) | undefined;
    if (page) {
      page().then((response) => {
        component = response;
      }).catch(() => null);
    } else {
      component = null;
    }
  });
  onDestroy(unsubscribe);
</script>

{#if component !== null}
  <svelte:component this={component.default} {locale} />
{/if}
